### ISSUE TITLE
hm.each() iterates over .length property of HTMLCollection

### ISSUE THREAD

**Issue by estelsmith** [cameroncondry/cbc-helpme#3]
hm.each() iterates over the .length property in Chrome 39 on Mac OS X, but does not in Mozilla Firefox 33.1.

jQuery does not iterate over .length in any case, and it would be nice to make the hm library's API consistent.

To reproduce:
```javascript
// Assume this contains 3 elements
var elements = document.getElementsByTagName('div');

hm.each(elements, function (index, element) {
    console.log(index);
});

/*
 * Output - Chrome 39, Mac OS X
 * 0
 * 1
 * 2
 * length
 *
 * Output - Firefox 33.1, Mac OS X
 * 0
 * 1
 * 2
 */
```

**Comment by cameroncondry** [comment]
Thank you for the report, this has been solved.
